# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='complains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.IntegerField()),
                ('text', models.CharField(max_length=2000)),
                ('submit_date', models.DateField()),
                ('proceed_date', models.DateField()),
                ('status', models.CharField(max_length=4)),
                ('manager_id', models.IntegerField()),
                ('reply', models.CharField(max_length=2000)),
                ('score', models.IntegerField()),
                ('follow_cmplt_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.IntegerField()),
                ('name', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('reg_time', models.DateField()),
                ('supplier_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('name', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_id', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=20)),
                ('producer', models.CharField(max_length=40)),
                ('supplier_id', models.IntegerField()),
                ('price', models.IntegerField()),
                ('count', models.IntegerField()),
                ('remain', models.IntegerField()),
                ('type', models.CharField(max_length=10)),
                ('imagepath', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='managers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_id', models.IntegerField()),
                ('name', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('reg_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('good_str', models.CharField(max_length=50)),
                ('goods_num', models.CharField(max_length=50)),
                ('customer_id', models.IntegerField()),
                ('manager_id', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('submit_date', models.DateField()),
                ('finish_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='suppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='supply_orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_order_id', models.IntegerField()),
                ('supplier_id', models.IntegerField()),
                ('good_str', models.CharField(max_length=50)),
                ('goods_num', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=4)),
                ('submit_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('contact_id', models.IntegerField()),
                ('manager_id', models.IntegerField()),
            ],
        ),
    ]
