# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('complaint_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('text', models.TextField()),
                ('submit_date', models.DateField()),
                ('proceed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=4)),
                ('manager_id', models.IntegerField()),
                ('reply', models.TextField(blank=True, null=True)),
                ('follow_cmplt_id', models.IntegerField(blank=True, null=True)),
                ('source_cmplt_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Complaints',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('contact_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('reg_time', models.DateField()),
                ('supplier_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('temp_order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('comment', models.TextField()),
                ('place', models.CharField(max_length=20)),
                ('producer', models.CharField(max_length=40)),
                ('supplier_id', models.IntegerField()),
                ('price', models.IntegerField()),
                ('count', models.IntegerField()),
                ('remain', models.IntegerField()),
                ('type', models.CharField(max_length=10)),
                ('image_path', models.CharField(blank=True, max_length=100)),
                ('website', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'Goods',
            },
        ),
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('reg_time', models.DateField()),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Managers',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_temp', models.IntegerField()),
                ('good_str', models.CharField(blank=True, max_length=100, null=True)),
                ('good_num', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_id', models.IntegerField()),
                ('manager_id', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('submit_date', models.DateField(blank=True, null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('supplier_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='Supply_orders',
            fields=[
                ('supply_order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('supplier_id', models.IntegerField()),
                ('good_str', models.CharField(max_length=50)),
                ('goods_num', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=4)),
                ('submit_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('contact_id', models.IntegerField()),
                ('manager_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Supply_orders',
            },
        ),
    ]
