# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complains',
            name='id',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='id',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='id',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='id',
        ),
        migrations.RemoveField(
            model_name='managers',
            name='id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='id',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='id',
        ),
        migrations.RemoveField(
            model_name='supply_orders',
            name='id',
        ),
        migrations.AlterField(
            model_name='complains',
            name='complaint_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='contact_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customers',
            name='customer_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='goods',
            name='good_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='managers',
            name='manager_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='supplier_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supply_orders',
            name='supply_order_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
