# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='follow_cmplt_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='proceed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='good_num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='good_str',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='submit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
