# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20171214_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='complains',
            name='complaint_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='complains',
            name='reply',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='complains',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='contact_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customers',
            name='customer_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='goods',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='goods',
            name='good_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='goods',
            name='imagepath',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='managers',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='managers',
            name='manager_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='supplier_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supply_orders',
            name='supply_order_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
