# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20171215_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('complaint_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('text', models.TextField()),
                ('submit_date', models.DateField()),
                ('proceed_date', models.DateField()),
                ('status', models.CharField(max_length=4)),
                ('manager_id', models.IntegerField()),
                ('reply', models.TextField()),
                ('follow_cmplt_id', models.IntegerField()),
                ('source_cmplt_id', models.IntegerField()),
            ],
            options={
                'db_table': 'complaints',
            },
        ),
        migrations.DeleteModel(
            name='complains',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='imagepath',
            new_name='image_path',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='goods_num',
            new_name='good_num',
        ),
        migrations.AddField(
            model_name='customers',
            name='password',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customers',
            name='temp_order',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='managers',
            name='password',
            field=models.CharField(default='aaa', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='is_temp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers',
            name='customer_id',
            field=models.IntegerField(db_column='Fld', primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='contacts',
            table='contacts',
        ),
        migrations.AlterModelTable(
            name='customers',
            table='customers',
        ),
        migrations.AlterModelTable(
            name='goods',
            table='goods',
        ),
        migrations.AlterModelTable(
            name='managers',
            table='managers',
        ),
        migrations.AlterModelTable(
            name='orders',
            table='orders',
        ),
        migrations.AlterModelTable(
            name='suppliers',
            table='suppliers',
        ),
        migrations.AlterModelTable(
            name='supply_orders',
            table='supply_orders',
        ),
    ]
